### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by jhasuman** [naokishibuya/traffic-sign-classification#1]
Hi I have downloaded all the Data files and insert into the car-traffic-sign-classification-master as GSTRB folder and trying to follow the steps in Notebook. But getting this ValueError: No objects to concatenate. I am also attaching the error pic.  Thank You!! 
url = https://drive.google.com/file/d/0B9l6wLTrMbENbkxUaEs0emkxYVE/view

**Comment by naokishibuya** [comment]
Hi @jhasuman 
The error indicates the `dfs` is empty hence the line `pd.concat(dfs, ...)` failed.  So, I'm guessing the .csv files are not at where they are expected.  

If you have the following data folder structure, it should be able to load but it's hard for me to know as I can not see your folder structure.

```
data
 + Final_Training
    + Images
        + 00000
            + 00000_00000.ppm
            + 00000_00001.ppm
            ...    
            + GT-00000.csv
        + 00001
            + 00000_00000.ppm
            + 00000_00001.ppm
            ...    
            + GT-00001.csv
        ...
```

I'd suggest adding some print lines in the following code to see if data is loaded properly.

```python
TRAIN_IMAGE_DIR = 'data/Final_Training/Images'

dfs = []
for train_file in glob.glob(os.path.join(TRAIN_IMAGE_DIR, '*/GT-*.csv')):
    folder = train_file.split('/')[3]
    df = pd.read_csv(train_file, sep=';')

    # TODO print the content of df to see if it loaded data correctly

    df['Filename'] = df['Filename'].apply(lambda x: os.path.join(TRAIN_IMAGE_DIR, folder, x))
    dfs.append(df)
```

Let me know how that goes.

**Comment by jhasuman** [comment]
Hello, 

My data folder structure seems good, you can also have a look. But now I am getting "List Index out of range"  

![data_formate](https://user-images.githubusercontent.com/17616710/31036540-53e19332-a58a-11e7-903b-71eda6e23807.png)
![error](https://user-images.githubusercontent.com/17616710/31036546-58ec9494-a58a-11e7-8b80-6f774a1ddad7.jpg)
Thank You!!

**Comment by naokishibuya** [comment]
Hi @jhasuman,

Thanks for the above image.  I can see your folder structure now.   

I think your notebook (Traffic_Sign_Classifier.ipynb) is inside `car-traffic-sign-classification-master` folder, right?  

As the `data` folder should be in the same directory as the notebook (Traffic_Sign_Classifier.ipynb), you can either move your data folder there or else, you can adjust `TRAIN_IMAGE_DIR` variable to your `data` folder location.  

Hope that solves the problem.  Let me know how it goes!

**Comment by jhasuman** [comment]
Hi Still same error. 
If you can share your Skype id, will be much helpful!! 

![error](https://user-images.githubusercontent.com/17616710/31044888-c5e50dfe-a5f5-11e7-8dbf-d22f7a783636.png)

**Comment by naokishibuya** [comment]
Hi @jhasuman,

I'm wondering if this is some Windows specific problem.  My environment is macOS / Linux.

Can you try loading a CSV file using the following statement in your environment?

```
pd.read_csv(train_file, sep=';')
```
The `train_file` above should be a path to your csv file.  For example, `'data/Final_Training/Images/00000/00000_00000.ppm'`.

Or do you need to use a backslash?

`'data\Final_Training\Images\00000\00000_00000.ppm'`

If so, we may need to use `os.path.join` to compose a path.

One more thing I want to know is that if the below split works on Windows?

```
folder = train_file.split('/')[3]
```

Or do we need to use the backslash `'\'` instead of the forward slash `'/'`?

If so, we may need to use `os.sep` to make the code work for all environment.

**Comment by naokishibuya** [comment]
Sorry pressed the wrong button and closed it.  Reopening the issue.

**Comment by jhasuman** [comment]
After loading the csv file. 

It seems I am making some small error, but don't unable to identify. 
![error](https://user-images.githubusercontent.com/17616710/31045891-2faffb58-a60b-11e7-91be-04a10500494a.png)

**Comment by naokishibuya** [comment]
ok, so you need to use `'\\'` instead of `'/'` on Windows, right? 

```python
TRAIN_IMAGE_DIR = 'data\\Final_Training\\Images'

dfs = []
for train_file in glob.glob(os.path.join(TRAIN_IMAGE_DIR, '*\\GT-*.csv')):
    folder = train_file.split('\\')[3]
    df = pd.read_csv(train_file, sep=';')
    df['Filename'] = df['Filename'].apply(lambda x: os.path.join(TRAIN_IMAGE_DIR, folder, x))
    dfs.append(df)
```

Can you try this to see if it works?  

Or you can try something like below using `os.sep` and `os.path.join` (note: the below is an untested code).

```python
TRAIN_IMAGE_DIR = os.path.join('data', 'Final_Training', 'Images')

dfs = []
for train_file in glob.glob(os.path.join(TRAIN_IMAGE_DIR, '*', 'GT-*.csv')):
    folder = train_file.split(os.sep)[3]
    df = pd.read_csv(train_file, sep=';')
    df['Filename'] = df['Filename'].apply(lambda x: os.path.join(TRAIN_IMAGE_DIR, folder, x))
    dfs.append(df)
```
The second one is prefered solution as it should work for macOS, Linux and Windows.

**Comment by jhasuman** [comment]
Still same error, I am attaching my entire structure. It seems I am missing some things. 
![error1](https://user-images.githubusercontent.com/17616710/31047270-1ccf9394-a625-11e7-8b7b-cfb94fb6a970.jpg)

![error2](https://user-images.githubusercontent.com/17616710/31047272-25a5c70e-a625-11e7-9035-f10ef21ddff6.jpg)

**Comment by naokishibuya** [comment]
Hi @jhasuman 
I see `Traffic_Sign_Classifier.ipynb` in two places in the above images.  Which one are you using?

I assume the below is the content of the `data` folder.  `Traffic_Sign_Classifier.ipynb` here should not be used.  

![image](https://user-images.githubusercontent.com/1075889/31050203-5417fc50-a676-11e7-981a-7e54b886cb39.png)

Also, if you put `print` statements like below, do you see any file/folder name printed?  If not, it is not finding files.

```python
TRAIN_IMAGE_DIR = os.path.join('data', 'Final_Training', 'Images')

dfs = []
for train_file in glob.glob(os.path.join(TRAIN_IMAGE_DIR, '*', 'GT-*.csv')):
    print(train_file)  # <== print the file name
    folder = train_file.split(os.sep)[3]
    print(folder)  # <== print the folder name
    df = pd.read_csv(train_file, sep=';')
    df['Filename'] = df['Filename'].apply(lambda x: os.path.join(TRAIN_IMAGE_DIR, folder, x))
    dfs.append(df)
```

**Comment by naokishibuya** [comment]
Hi @jhasuman 
I'm closing this for now.  If you have any other questions or findings related to this issue, please re-open it for further discussion.
