### ISSUE TITLE
Got this error when running the code right under The First Performance.

### ISSUE THREAD

**Issue by EasonChan236** [naokishibuya/traffic-sign-classification#2]
TypeErrorTraceback (most recent call last)
<ipython-input-35-e1ebf1038547> in <module>()
      1 with Session() as session:
      2     functions = [loader]
----> 3     pipeline = build_pipeline(functions, session, make_network1(), make_adam(1.0e-3))
      4     train_evaluate(pipeline)

<ipython-input-27-91941b9e2ddc> in make_network1(input_shape)
      3 def make_network1(input_shape=INPUT_SHAPE):
      4     return (NeuralNetwork()
----> 5             .input(input_shape)
      6             .conv([5, 5, 6])
      7             .max_pool()

/home/linux/dsmlp/70/770/cg181fcp/final_project/pipeline/network.py in input(self, shape)
     57         """
     58         with self.variable_scope('input'):
---> 59             self.x = tf.placeholder(tf.float32, (None, shape),name='x')
     60             self.y = tf.placeholder(tf.int64, (None), name='y')
     61             self.is_training = tf.placeholder(tf.bool, name='is_training')

/opt/conda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.pyc in placeholder(dtype, shape, name)
   1603     evaluated directly.
   1604   """
-> 1605   return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
   1606 
   1607 

/opt/conda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.pyc in _placeholder(dtype, shape, name)
   3085   if shape is None:
   3086     shape = None
-> 3087   shape = _execute.make_shape(shape, "shape")
   3088   _ctx = _context.context()
   3089   if _ctx.in_graph_mode():

/opt/conda/lib/python2.7/site-packages/tensorflow/python/eager/execute.pyc in make_shape(v, arg_name)
    144     shape = tensor_shape.as_shape(v)
    145   except TypeError as e:
--> 146     raise TypeError("Error converting %s to a TensorShape: %s." % (arg_name, e))
    147   except ValueError as e:
    148     raise ValueError("Error converting %s to a TensorShape: %s." % (arg_name,

TypeError: Error converting shape to a TensorShape: int() argument must be a string or a number, not 'tuple'.

My tensorflow version is 1.4.0-dev20171012.

**Comment by naokishibuya** [comment]
Hi @EasonChan236 

I noticed two things:

I used Python 3.5 as specified in the environments.yml files.  In your error, you are using python 2.7.  This may or may not be an issue.

Another thing is that the version of TensorFlow I used is older than 1.4.  Unfortunately, I did not specify the exact version in the environment.yml or environment-gpu.yml so I am not certain which version I used.  

So, I would first try using python 3.5 in your environment.  If you still encounter an issue, please let me know.

**Comment by EasonChan236** [comment]
Hi @naokishibuya 

I am also thinking it may be the issue of the different version.
Trying to figure it out. Anyway, I really appreciate your contribution and fabulous work.

**Comment by naokishibuya** [comment]
Hi @EasonChan236 

I'm closing this issue for now as I haven't heard from you for some time.  Please reopen the issue if you need to further discuss the issue.
