### ISSUE TITLE
Always gives an output

### ISSUE THREAD

**Issue by AboHadi313** [naokishibuya/traffic-sign-classification#3]
Hello sir,
I'm working on the same project, for my senior.
I trained my model and everything is working fine if I am using pictures of traffic signs, but when I used a picture of a dog, it shows me that it is a: Road work!
I tried other pictures too, they are showing me the same thing, wrong detection.
So, what it is doing is always giving an output, even though there is nothing to detect in the picture!
Any idea how to solve this problem?
I thought about making a threshold for the probability, but it won't work all the time.
Is there any special function/method to do this, since I am new to CNN and TF, I do not know all capabilities of it.

**Comment by naokishibuya** [comment]
Hi @AboHadi313 
I would use a confidence (probability) level threshold as you already mentioned.  Good luck!
